// TypeScript interfaces
export interface Product {
    id?: number;
    type: string;
    name: string;
    secondary_name?: string;
    code: string;
    symbology?: string;
    category_id?: number;
    subcategory_id?: number;
    brand_id?: number;
    unit_id?: number;
    sale_unit_id?: number;
    purchase_unit_id?: number;
    cost?: number;
    price?: number;
    min_price?: number;
    max_price?: number;
    max_discount?: number;
    rack_location?: string;
    weight?: number;
    dimensions?: string;
    hsn_number?: string;
    sac_number?: string;
    supplier_id?: number;
    supplier_part_id?: string;
    alert_quantity?: number;
    video_url?: string;
    details?: string;
    featured: boolean;
    hide_in_pos: boolean;
    hide_in_shop: boolean;
    tax_included: boolean;
    can_edit_price: boolean;
    has_expiry_date: boolean;
    has_variants: boolean;
    dont_track_stock: boolean;
    set_stock: boolean;
    has_serials: boolean;
    title?: string;
    description?: string;
    keywords?: string;
    noindex: boolean;
    nofollow: boolean;
    photo?: string;
    products?: any[];
    taxes?: any[];
    unit_prices?: Record<string, { cost: number | null; price: number | null }>;
    variants: Array<{ name: string; options: string[] }>;
    variations: any[];
    stores: any[];
    serials: Array<{ number: string; till: string }>;
    extra_attributes?: Record<string, any>;
    file?: File[];
    photos?: File[];
}
